# Generated by Django 4.0.6 on 2022-09-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=56)),
                ('puuid', models.CharField(max_length=78)),
                ('monitored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=16)),
                ('rank', models.PositiveIntegerField()),
                ('lp', models.IntegerField(default=0)),
                ('tops', models.PositiveIntegerField(default=0)),
                ('bottoms', models.PositiveIntegerField(default=0)),
                ('orderable_rank', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='rankhistory',
            index=models.Index(fields=['player', '-timestamp'], name='players_ran_player__839f90_idx'),
        ),
    ]
